# fly.toml app configuration file generated for mentiman on 2023-11-13T21:48:08+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mentiman"
primary_region = "otp"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
